.github/workflows/update_docker.yml, ros/kinetic.Dockerfile, ros/melodic.Dockerfile, ros/noetic.Dockerfile, ros2/crystal.Dockerfile, ros2/dashing.Dockerfile, ros2/eloquent.Dockerfile, ros2/foxy.Dockerfile, template/ros.dockerfile.jinja, template/ros2.dockerfile.jinja, update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/2)
=> added gazebo target to ros based dockerfiles

.github/workflows/automerge.yml, .github/workflows/update_docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/4)
=> added automerge workflow

.github/workflows/check_docker.yml, .github/workflows/push_docker.yml, .github/workflows/update_docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/7)
=> cancel runs from old commits

.github/workflows/check_docker.yml, .github/workflows/push_docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/8)
=> updated dockerfile workflow names

update.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/13)
=> increased timeout in script

.devcontainer/devcontainer.json, .github/workflows/check_docker.yml, .github/workflows/publish_docs.yml, .github/workflows/push_docker.yml, .gitignore, README.md, build.py, generate.py, mkdocs.yml, requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/14)
=> added autodocs

.github/workflows/push_docker.yml, .vscode/tasks.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/16)
=> added tasks, cleaned up push

.github/workflows/automerge.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/18)
=> updated automerge settings

.github/workflows/publish_docs.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/21)
=> Changed environment variable for site url

.github/workflows/autosquash.yml, .github/workflows/bot.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/24)
=> updated workflow names

.github/dependabot.yml, .github/workflows/autosquash.yml, .github/workflows/check_docker.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athackst/dockerfiles/25)
=> updates so workflow triggers after status complete

.vscode/settings.json
chore(vscode): update config for python interpreter in vscode config
Test:
- before change
- after change
=> chore(vscode): update config for python interpreter in vscode config

ros2/humble-cuda.Dockerfile, ros2/humble.Dockerfile, template/ros2.dockerfile.jinja
=> Change pylint install target from pylint3 to pylint for humble

ros2/foxy-cuda.Dockerfile, ros2/humble-cuda.Dockerfile, templates.yml
=> Upgrade base image version from cuda 11.7.0 to 11.8.0

.github/workflows/docker.yml, build.py, generate.py, requirements.txt
Begin of refactor that will address #177 and #275
=> Use matrix to build docker files with buildx

README.md, build.py
=> Add target to build script

ros2/humble-cuda.Dockerfile, ros2/humble.Dockerfile, ros2/iron-cuda.Dockerfile, ros2/iron.Dockerfile, template/ros2.dockerfile.jinja
Related: https://github.com/athackst/vscode-ament-task-provider/pull/201
=> Add ament packages to dev image

.github/workflows/docker.yml, .vscode/tasks.json, ros2/README.md, ros2/rolling.Dockerfile, templates.yml
Hello :)
I find your work very useful. I am developing nav2 packages and want to make use of your great tools. I need support for rolling which is not supported yet. Please provide the list of the things that needs to be done to make this work. I was able to build this image and push it to my own docker hub, then locally use it as base in vscode_ros2_workspace.
=> Add skeleton for rolling support

.github/workflows/docker.yml, .vscode/tasks.json, ros2/README.md, ros2/humble-cuda.Dockerfile, ros2/humble.Dockerfile, ros2/iron-cuda.Dockerfile, ros2/iron.Dockerfile, ros2/jazzy.Dockerfile, template/ros2.dockerfile.jinja, template/snippits/ros2_user.jinja, templates.yml
It doesn't look like there's a [cuda image](https://hub.docker.com/r/nvidia/cuda/tags?page=&page_size=&ordering=&name=) for 24.04 
Ubuntu 24.04 now comes with an "ubuntu" user on 1000:1000 as the nonroot user.  This PR deletes that user in favor of the "ros" user to match previous images.
Closes #456
=> Add jazzy to dockerfiles

.github/workflows/docker.yml, .vscode/tasks.json, ros2/humble-cuda.Dockerfile, ros2/humble.Dockerfile, ros2/iron-cuda.Dockerfile, ros2/iron.Dockerfile, ros2/jazzy.Dockerfile, ros2/rolling.Dockerfile, template/ros2.dockerfile.jinja, template/snippits/ros2_user.jinja, templates.yml
Reverts athackst/dockerfiles#499
=> Revert "Fix user settings"

.github/workflows/docker.yml, .vscode/tasks.json, requirements.txt, ros2/README.md, ros2/rolling-cuda.Dockerfile, templates.yml
I just wanted to use image but I see that [PR#521](https://github.com/athackst/dockerfiles/pull/521]) stuck.
I've just run generate script and added results to the PR.
=> Adding rolling cuda image

.github/workflows/docker.yml, .github/workflows/test.yml
Reverts athackst/dockerfiles#543
=> Revert "Update workflows for all pull request tests in test.yml"

.github/workflows/docker.yml, .github/workflows/test.yml
Reverts athackst/dockerfiles#544
Restores filter check.
=> Restore "Update workflows for all pull request tests in test.yml"

.github/workflows/docker.yml, .vscode/tasks.json, ros2/README.md, ros2/jazzy-cuda.Dockerfile, templates.yml
=> Add jazzy-cuda dockerfile

docker-compose/README.md, docker-compose/gz/harmonic-docker-compose.yml, docker-compose/gz/ionic-docker-compose.yml, generate.py, template/gz.docker-compose.yml.jinja
This should allow you to run gazebo with GUI 
Tested on Ubuntu 24.04
Closes #441
=> Add docker compose files for gz

.github/actions/docker-build-push/README.md, .github/actions/docker-build-push/action.yml, .github/workflows/docker.yml
Adds a docker-build-push local action to skip all steps in matrix if unchanged
=> Add docker-build-push local action
